### ISSUE TITLE
How to create a custom scalar?

### ISSUE THREAD

**Issue by lgaches** [GraphQLSwift/Graphiti#1]
How can I create a custom scalar for Date ?

**Comment by paulofaria** [comment]
sorry for the delay! yeah I think I forgot to add a Graphiti type for a scalar haha. I'll do it as soon as I get some free time. so busy these days. if you have anything ready, let me know. feel free to send a PR. 😊

**Comment by paulofaria** [comment]
You saw the update adding this right? (:
