### ISSUE TITLE
Federation N+1 query problem

### ISSUE THREAD

**Issue by ZirgVoice** [GraphQLSwift/Graphiti#101]
In schema in key i can't return an array
```swift
        Type(ProductUser.self, as: "User") {
            Field("email", at: \.email)
            Field("name", at: \.name)
            Field("totalProductsCreated", at: \.totalProductsCreated)
            Field("yearsOfEmployment", at: \.yearsOfEmployment)
            Field("averageProductsCreatedPerYear", at: \.averageProductsCreatedPerYear)
        }.key(at: ProductResolver.getUsers) {
            Argument("email", at: \.email)
        }
```
This is necessary to solve the [N+1 problem]( https://www.apollographql.com/docs/technotes/TN0019-federation-n-plus-1/#writing-efficient-entity-resolvers)

Now I'm using [graphql-transform-federation](https://github.com/0xR/graphql-transform-federation) it has [batchDelegateToSchema from graphql-tools](https://github.com/ardatan/graphql-tools/blob/master/packages/batch-delegate/tests/basic.example.test.ts#L64), I tried to do something similar via DataLoader but I can't return the result because it's an array

**Comment by NeedleInAJayStack** [comment]
Why weren't you able to use [DataLoader](https://github.com/GraphQLSwift/DataLoader) to address this? You can definitely create a resolver function that uses a DataLoader that returns a single object (not an array), thereby addressing the N+1 problem.

**Comment by ZirgVoice** [comment]
Oh right, I forgot about that, thanks!
