### ISSUE TITLE
'Identifiable' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by broosted** [GraphQLSwift/Graphiti#119]
<img width="1383" alt="image" src="https://github.com/GraphQLSwift/Graphiti/assets/10822418/52a2a0c3-8209-4311-9b16-e7a4643745bb">
Only imported Graphiti to a TestProj and getting above error in Xcode
iOS 16.4
Swift5

**Comment by NeedleInAJayStack** [comment]
Thanks for reporting!

I tested that the PR I put in above fixes this issue, but could you double-check @broosted?

**Comment by broosted** [comment]
the PR looks good once its in main I will update package in my TestProj
