### ISSUE TITLE
Bearer and basic authorization

### ISSUE THREAD

**Issue by Fa1zer** [GraphQLSwift/Graphiti#122]
HI! I need to use bearer and basic authorization in my Vapor Graphiti server app. I just need to add middleware to my route. How can I do this?
When I wasn't using GraphQL I did something like this:
```
func boot(routes: RoutesBuilder) throws {
        routes.grouped("users").grouped(UserToken.authenticator()).webSocket("update", onUpgrade: self.webSocket)
    }
```
Can I do a similar thing using Graphiti?

**Comment by NeedleInAJayStack** [comment]
Yup, you can do exactly the same thing. Graphiti doesn't have anything to do with the Vapor HTTP apis, it really just handles defining GraphQL schemas and executing queries. Typically you'd define a Graphiti API object, instantiate it on Vapor startup, and then execute queries against it within a POST or GET request definition. That POST or GET request can have authentication middleware in the normal Vapor way.
