### ISSUE TITLE
Would it make sense to make NoArguments init public?

### ISSUE THREAD

**Issue by cshadek** [GraphQLSwift/Graphiti#124]
Right now `NoArguments.init` is not public, so it appears to me that you can't call a function in your resolver that uses `NoArguments`.  It would sometimes be nice to be able to make an instance of `NoArguments` in order to call these resolver functions directly.

**Comment by NeedleInAJayStack** [comment]
Sure, I see no problem with that at all. Could you create a quick MR for it?

**Comment by cshadek** [comment]
Sure - I'll get right on it.  On a similar note, I was thinking it may make sense to make `PageInfo` have a public init to make it easier to create custom connections.  I'll make both changes and then create a pull request
