### ISSUE TITLE
Update to work with GraphQLSwift 0.4.0

### ISSUE THREAD

**Issue by AttilaTheFun** [GraphQLSwift/Graphiti#14]
I just started playing around with your other library, but was disappointed to find out that the latest version doesn't work with Graphiti. I tried forking the library and updating the Package.swift file, but there are a bunch of compile errors mostly due to changes in your Runtime dependency that I wasn't sure how to resolve. It would be great if these two could work together again.

**Comment by paulofaria** [comment]
fixed by #15
