### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by Nodepad** [GraphQLSwift/Graphiti#22]
Are there any way to create subscription in Graphiti/GraphQL? I have found method `subscription()` in `SchemaBuilder` but could not understand how to do actual data notification.

**Comment by paulofaria** [comment]
Hello, sorry for the delay. We don't provide support for subscriptions. Did you go further with this attempt?

**Comment by Nodepad** [comment]
I've tried to find a publish/subscribe Swift library for subscription implementation, but there is not much such staff, especially built on top of Apple NIO. Do you have ideas what library should be used?

**Comment by NeedleInAJayStack** [comment]
Hey, I'd like to implement subscriptions into this repo and the [GraphQLSwift/GraphQL](url) repo. I'm planning to use RxSwift to provide the [event streams](https://github.com/ReactiveX/RxSwift), similar to how the [Java GraphQL implementation](https://github.com/graphql-java/graphql-java) does it.

A few questions for the maintainers:
1. Do you forsee any significant architectural changes that will have to happen to implement the subscription event streaming into the resolvers?
2. Do you see any large roadblocks?

Thanks!

**Comment by NeedleInAJayStack** [comment]
I've submitted a pull request to add subscription support: https://github.com/GraphQLSwift/Graphiti/pull/52

Thanks!

**Comment by NeedleInAJayStack** [comment]
Hey @paulofaria, I think with my pull requests merged, we can close this issue. Thanks!!

**Comment by paulofaria** [comment]
@NeedleInAJayStack thank you!
