### ISSUE TITLE
EventLoop generic parameter

### ISSUE THREAD

**Issue by zdnk** [GraphQLSwift/Graphiti#24]
This seems a little unusable with Vapor 3 as you get passed `evenLoop` in request which is not the multithreaded one, but different which is internal to Swift NIO. So I cannot really make Graphiti work with Vapor 3. Maybe I am missing a thing or two?

`MultiThreadedEventLoopGroup` seems to me like the only one thats public.

**Comment by kimdv** [comment]
Hi @zdnk 

I have tried Graphiti with Vapor 3, and it worked fine! 

Have you tried this: `schema.execute(request: query, eventLoopGroup: req)` 

```
 try query.field(name: "questions",
                        type: [Question].self,
                        description: "",
                        resolve: {(_, _, context, worker, _) in
                            return Question.query(on: worker).all()
        })
```

**Comment by zdnk** [comment]
I see. I did not know `Request` is also `EventLoopGroup`. It would be nice to mention somewhere how to use this properly with Vapor 3.

**Comment by paulofaria** [comment]
New version of Graphiti won't have eventLoopGroup as a generic parameter. You won't have to specify the eventLoopGroup type anymore.
