### ISSUE TITLE
Is there an HTTP Server reference/example that uses Graphiti?

### ISSUE THREAD

**Issue by mishagray** [GraphQLSwift/Graphiti#33]
This project is very interesting to me... but I wonder if there are any full graphql server implementations, aka: a swift server implementation that would be similar to Apollo Server (with authentication, HTTPS, etc) and compatible with existing Apollo GraphQL clients for Javascript and IOS (and other graphql clients).     

I could definitely see building such a thing, and have been searching to see if anyone has at least a start/reference implementation on GitHub.

Would totally be interested in contributing to a project like that.

**Comment by alexsteinerde** [comment]
I shared an article about how to implement a GraphQL server with Vapor and Swift lately: https://medium.com/@alexsteinerde/how-to-build-a-graphql-server-with-swift-and-vapor-ec202c2d4318?source=friends_link&sk=27e5ffcfc250069f6b9291bcada520db Feel free to contribute to any related project. Also feedback is always welcome.

**Comment by NeedleInAJayStack** [comment]
This is a great project that seeks to integrate GraphQL with an HTTP server: https://github.com/d-exclaimation/pioneer/blob/main/Package.swift
