### ISSUE TITLE
Allow enum cases to be inferred if type conforms to `CaseIterable`

### ISSUE THREAD

**Issue by alexsteinerde** [GraphQLSwift/Graphiti#36]
Currently you have to specify each case of an enum in the `Schema` type if you want to use it. This makes sense in case you want to only expose a specific range of cases to your public api. 
But most of the times you want to expose all cases. So, a generalised function that infers all cases by requiring the protocol `CaseIterable` on the enum type.

An implementation could look like this.
```swift
extension Enum where EnumType: CaseIterable {
    public convenience init(
        _ type: EnumType.Type,
        name: String? = nil
    ) {
        self.init(type, name: name, EnumType.allCases.map({ Value($0) }))
    }
}
```

Do you think that this could also be useful for others? Is there any feedback on the idea?

**Comment by paulofaria** [comment]
Earlier versions of the library allowed things like this. For example, it was possible to simply set the  Swift type for a GraphQL type and we would use reflection to expose all of the properties as GraphQL fields automatically. I eventually arrived at the conclusion that that wasn't a good idea so now we require everything to be exposed explicitly. The main goal is to have the schema be like a mirror to a GraphQL schema file. No hidden surprises. You read the schema, you know the truth.

**Comment by paulofaria** [comment]
Another reason to require the schema to be explicit is that it might encourage developers to add descriptions to the API. With reflection or `CaseIterable`, for example, we wouldn't have a proper way to add descriptions.
