### ISSUE TITLE
Function Builder type inferring is not working

### ISSUE THREAD

**Issue by alexsteinerde** [GraphQLSwift/Graphiti#37]
Function builders provide a great usability especially for DSLs like Graphiti has build in.
But at the moment Function builders are still in a private-like state in the Swift development process. This can be seen on the underscore in front of the function name(`@_functionBuilder`). 
It also makes some trouble in current Swift versions by not inferring types of the GraphQL schema builder classes.
I created a fork (https://github.com/alexsteinerde/Graphiti) and tried a temporary alternative for function builders: Arrays. It is not the perfect solution and when function builders will be working they should be used again but until then I think this is the best way to go at the moment.

Do you think this is an implementation that could be merged back into this repository to make it easier to discover by other and to make further development possible here?

**Comment by paulofaria** [comment]
This is fixed by the last version.
