### ISSUE TITLE
Is there a plan in place for adding support for async await?

### ISSUE THREAD

**Issue by cshadek** [GraphQLSwift/Graphiti#55]
Async-await will be added in Swift 5.5.  
https://github.com/apple/swift-evolution/blob/main/proposals/0296-async-await.md

**Comment by cshadek** [comment]
Given that Swift 5.5 is now released, will Graphiti support async-await?

**Comment by alobaili** [comment]
Hello @cshadek, @paulofaria and @adam-fowler
For organization, I think this issue should be reopened and linked to https://github.com/GraphQLSwift/Graphiti/pull/71

It appears that support for async/await is a big undertaking. I really hope to see it implemented some day.

I've just started learning about this package from https://www.raywenderlich.com/21148796-graphql-tutorial-for-server-side-swift-with-vapor-getting-started

It's a great package, thank you all for your hard work!

**Comment by paulofaria** [comment]
Hi, thank you for your kindness. I will try to finish this by the end of the month. The async part itself is mostly done. It's just that I took the chance to improve the API so we can release a new major version and life got in the way.

**Comment by paulofaria** [comment]
I was also waiting on https://github.com/apple/swift-evolution/blob/main/proposals/0348-buildpartialblock.md to improve the API greatly. Instead of using classes and initializers for the Schema definition, we'll be able to use functions and structs, which will make the API look much closer to the GraphQL SDL.

**Comment by cshadek** [comment]
> @cshadek I have done a little thinking about subscriptions and async/await. The new [AsyncSequence](https://developer.apple.com/documentation/swift/asyncsequence) should be able to replace reactive drivers like [GraphQLRxSwift](https://github.com/GraphQLSwift/GraphQLRxSwift).

This sounds amazing

**Comment by cshadek** [comment]
Yeah I just found it earlier today.  I really wonder if there shouldn't be some strategic partnership between Pioneer and GraphQLSwift.  It's almost like they want to build Apollo Server for Swift - that would be incredible!

**Comment by NeedleInAJayStack** [comment]
I have an [MR into GraphQL](https://github.com/GraphQLSwift/GraphQL/pull/100) that adds async/await support, and a followup one ready for Graphiti once that one goes through.

**Comment by d-exclaimation** [comment]
> Woah, I hadn't seen that repo before! That's pretty awesome stuff they're doing! Yeah, it seems like we could easily bring some of the extensions they've made into this repo.

I think I can help move the async-await extensions I made from [Pioneer](https://github.com/d-exclaimation/pioneer) here. The only problem with those extensions I made is that at the moment, they completely ignore the Sendable conformance which is not enforced now with Swift 5 but will be a problem later on with [Swift 6](https://forums.swift.org/t/concurrency-in-swift-5-and-6/49337) which is set to be safe-by-default and the only solution I see is `@_unsafeSendable` attribute but I haven't played with it yet.

**Comment by NeedleInAJayStack** [comment]
I'm marking this as resolved, since `async`/`await` support was added by https://github.com/GraphQLSwift/Graphiti/pull/78
