### ISSUE TITLE
Async Resolving

### ISSUE THREAD

**Issue by lightsprint09** [GraphQLSwift/Graphiti#6]
Hey. I  want to resolve a query like the following

```swift
try schema.query { query in
        try query.field(name: "stations", type: Array<Station>.self) { x, y, z, m in
           networkcall({result in
              ???? //How to resolve from here
           }
        }
        
    }
```

Keep up the work

**Comment by paulofaria** [comment]
@lightsprint09 Hey Lukas! Async resolving is not supported yet. If you're interested in contributing that would be great! (:

**Comment by lightsprint09** [comment]
Ok. I would give it a try.

Do I need to add support for async resolving in [GraphQL](https://github.com/GraphQLSwift/GraphQL) first, or just add it to Graphiti

**Comment by paulofaria** [comment]
@lightsprint09 GraphQL first! 😉

**Comment by lightsprint09** [comment]
I started digging threw the code. But I feeling not comfortable  to build such a big feature. It feels to me like the whole thing was build for synchrony queries.

**Comment by lightsprint09** [comment]
Ok. I will take a look at those files.
