### ISSUE TITLE
`@_functionBuilder` has been renamed to `@resultBuilder`

### ISSUE THREAD

**Issue by CrownedPhoenix** [GraphQLSwift/Graphiti#60]
As of Swift 5.4 [`@_functionBuilder` has been renamed to `@resultBuilder`](https://github.com/apple/swift-evolution/blob/main/proposals/0289-result-builders.md#changes-from-the-first-revision).

<img width="595" alt="Screen Shot 2021-05-18 at 2 52 11 PM" src="https://user-images.githubusercontent.com/34900063/118723388-97168d80-b7ea-11eb-8393-a754ab6b060a.png">

**Comment by NeedleInAJayStack** [comment]
@CrownedPhoenix This was resolved recently by PR https://github.com/GraphQLSwift/Graphiti/pull/62
