### ISSUE TITLE
Question: What is the right way to access 1 to 1 connection (@OptionalChild)

### ISSUE THREAD

**Issue by itayAmza** [GraphQLSwift/Graphiti#67]
I'm not really sure how to set optional child field on my schema, and access it as a connection.

I've got a User model, with Record as an optional child:
```
public final class User: Model {
    public static let schema = "users"
    
    @ID(key: .id)
    public var id: UUID?
    
    @OptionalField(key: "name")
    public var name: String?

    //MARK: Relations
    @OptionalChild(for: \.$user)
    public var record: Record?

    public init() { }

    public init(id: UUID? = nil,
                about: String? = nil) {
        self.id = id
        self.name = name
    }
}
```

The Record model:
```
public final class Record: Model {
    public static let schema = "records"
    
    @ID(key: .id)
    public var id: UUID?
    
    @Field(key: "type")
    public var type: Int
    
    //MARK: Relations
    @OptionalParent(key:"user_id")
    public var user: User?

    public init() { }

    public init(id: UUID? = nil,
                type: Int,
                userId: UUID? = nil) {
        self.id = id
        self.type = type
        self.$user.id = userId
    }
}
```
And I've defined my scheme like:
```
let schema = try! Schema<Resolver, Request> {
    Scalar(UUID.self).description("Unique ID Type")
    
    Type(User.self) {
        Field("id", at: \.id)
        Field("name", at: \.name)
        
        Field("record", at: \.$record, as: TypeReference<Record>?.self)
        //Field("record", at: \.$record, as: Record?.self) - also not working
    }
    
    Type(Record.self) {
        Field("id", at: \.id)
        Field("type", at: \.type)
        
        Field("user", with: \.$user)
    }
    
    Query {
        Field("user", at: Resolver.getUser) {
            Argument("id", at: \.id)
        }

        ...addUser
        ...addRecordToUser
    }
}
```

So I'm adding a user, and a record to this user ID, but when querying the user with its record field I get `Expected value of type \"Record\" but got: Child<User, Record>(for: [user_id]).`
What am I doing wrong here?

**Comment by alexsteinerde** [comment]
Graphiti has not built-in support for Vapor or Fluent specific types. Graphiti is a lower level building block to create GraphQL apis.
You can write your own resolver to handle Fluent queries. Or you may checkout this package (disclaimer: I'm the author): https://github.com/alexsteinerde/graphql-kit. 
I just pushed the `OptionalChild` support. Maybe you want to try this out. The usage is explained in the readme or you can find example code in the vapor-graphql-template repository I published as well.

**Comment by itayAmza** [comment]
I do use graphql-kit, for some reason 2.4 is not available yet, but that's good news.
Great work man, you got some awesome repos, Thanks.
