### ISSUE TITLE
Example of using subscriptions with Vapor

### ISSUE THREAD

**Issue by cshadek** [GraphQLSwift/Graphiti#77]
Has anyone tried this?  I assume we have to use Vapor's websocket API.  Is that correct?

**Comment by NeedleInAJayStack** [comment]
Yes, I'm doing it successfully. Here's a quick example of how you can do it:

```
func routes(_ app: Application, apiBuilder: OpenAPIBuilder) throws {
    routes.webSocket(
        "graphqlSubscribe",
        shouldUpgrade: { request in
            negotiateWebSocketSubProtocol(req: request)
        },
        onUpgrade: { request, websocket in
            context = Context(db: app.db)
            request.graphQLSubscribe(
                websocket: websocket,
                on: self.api,
                auth: { authToken in
                    try request.jwt.verify(authToken, as: UserToken.self)
                }
            )
        }
    )
}
```

**Comment by cshadek** [comment]
I ended up using a library called Pioneer that hides away some of the GraphiQL, websocket, and other hosting logic.  It also has a bunch of extensions to make Graphiti have async await support and even the subscriptions are asyncstreams too.

https://github.com/d-exclaimation/pioneer
