### ISSUE TITLE
Swift Compiler unable to type check long Schema expression

### ISSUE THREAD

**Issue by d-exclaimation** [GraphQLSwift/Graphiti#80]
It seemed like the Schema result builder failed to compile if the schema is over 800 lines long. The error message thrown here is that the compiler was unable to type check the expression in a reasonable time.

Not sure how to resolve this, I had thought that the One-way constraints shipped in 5.1.1 kinda helped the problem, but apparently not.

**Comment by d-exclaimation** [comment]
Nevermind

**Comment by NeedleInAJayStack** [comment]
Thanks for opening this - it's a good one to have as a reference for others. I've seen this error quite a bit and in every case I had made a syntax error or misaligned types. It is very frustrating that it doesn't provide a better suggestion on where the true issue lies, though.
