### ISSUE TITLE
Improvements to SchemaBuilder and allowing sub schemas

### ISSUE THREAD

**Issue by cshadek** [GraphQLSwift/Graphiti#85]
I really like the recent changes regarding circular dependencies and Type Reference.

Something that may go hand in hand with this would be to have a schema also be able to take in sub schemas.  Then you could define part of the schema in a different package and import it.  Think similar to how SwiftUI works with ViewBuilders.  I'm not sure how this would work with mutations and queries (since they effectively need to be combined at that level), but I think it would be useful.

Is this something that's been considered?

**Comment by NeedleInAJayStack** [comment]
Thanks @cshadek! I think adding a Builder-style pattern on top of Schema is a great idea! I've recently wanted the exact same thing, but haven't put any design or implementation effort in yet.

**Comment by cshadek** [comment]
Maybe a start would be to have something akin to Swift UI's Group {} construct.  Then you could Group parts of the schema together and define them somewhere else.

**Comment by NeedleInAJayStack** [comment]
Hey @cshadek , I took a stab at this in my most recent PR: https://github.com/GraphQLSwift/Graphiti/pull/87 

Note that it still requires all schema components to use the same `Resolver` and `Context` types, which might limit sub-schema definitions, but it at least makes it possible. It also makes splitting up a normal schema across files or packages much easier.

Thanks for the suggestion!

**Comment by cshadek** [comment]
Awesome!  Thanks for doing this @NeedleInAJayStack

**Comment by cshadek** [comment]
It seems to me that a good solution for sub schemas would be to have a base package with the definitions of Resolver and Context, but then create extensions of Resolver and possibly Context in "feature" packages (that could include their own sub schemas) and then have the package where the base schema is defined import those packages.  Then Resolver is effectively defined based on what features are imported.  @NeedleInAJayStack what do you think?  Would this work with the new schemabuilder?

**Comment by NeedleInAJayStack** [comment]
Yeah, that would definitely work with the new `SchemaBuilder` system.

**Comment by cshadek** [comment]
Do you think it's possible to do something similar to SwiftUI that would define schemas as their own Structs and therefore make declaring the schema truly declarative?

```
struct ChatsSchema: Schema {
    
    @SchemaTypesBuilder
    var types -> some ... {
        Type(Message.self) {
            Field("content", at: \.content)
        }
        Type(Chat.self) {
            Field("content", at: \.content)
        }
    }
    
    @SchemaQueryBuilder
    var queries -> some ... {
        Field("message", at: Resolver.message)
    }
    
    @SchemaMutationBuilder
    var mutations -> some ... {
        Field("sendMessage", at: Resolver.sendMessage)
    }
    
    // Make this optional?
    @SchemaSubcriptionBuilder
    var subscriptions -> some ... {
        
    }
}
```

And then somehow have the schema be able to build together multiple schemas.  This is just a quick attempt at what it could look like, but there are a lot of gaps that would need to be filled.  It could obviously use the builder under the hood.

**Comment by cshadek** [comment]
I'm also not sure this would be the best way to do something like this.  My goal in suggesting this is to make it truly declarative from the developer's standpoint and hide the builder logic.

**Comment by NeedleInAJayStack** [comment]
It might be possible. I'm honestly not very familiar with SwiftUI (mostly work on server-side Swift), and the ViewBuilder pattern is pretty complex to my unfamiliar eyes. I'm also not quite sure how this setup would support distributed schema definitions, but I could definitely be missing something. If you'd be willing to give it a shot, I'd be happy review or offer guidance.

Thanks for this feedback though. I have made a few adjustments to use `resultBuilder`s more widely throughout the `SchemaBuilder` functions.

**Comment by d-exclaimation** [comment]
I can probably take a look as this, so far I managed to get it working looking like this:

```swift
class AuthSchema: SubSchema<Resolver, Context> {
    @TypesDefinition
    override var types: Types {
        Type(User.self) {
            Field("name", at: \.name)
            Field("email", at: \.email)
        }
    }
    
    @FieldDefinition
    override var query: Fields {
        Field("me", at: Resolver.me)
    }
    
    @FieldDefinition
    override var mutation: Fields {
        Field("login", at: Resolver.login)
        Field("signup", at: Resolver.signup)
    }
}

class ChatsSchema: SubSchema<Resolver, Context> {
    @TypesDefinition
    override var types: Types {
        Type(Message.self) {
            Field("content", at: \.content)
        }
        Type(Chat.self) {
            Field("content", at: \.content)
        }
    }
    
    @FieldDefinition
    override var query: Fields {
        Field("message", at: Resolver.message)
    }
    
    @FieldDefinition
    override var mutation: Fields {
        Field("sendMessage", at: Resolver.sendMessage)
    }
}

let schema = try makeSchema([AuthSchema(), ChatsSchema()])
```

I guess the only caveat with this at the moment is that I am using `class` instead of `struct`, I would probably be able to create something similar using `struct` and `protocol` but I think I might need Swift 5.6 `any` keyword and Swfit 5.7 changes to `protocol` to do something like `any SubSchema<Resolver, Context>`

**Comment by d-exclaimation** [comment]
I might be able to create a PR for this later.

**Comment by d-exclaimation** [comment]
I have the PR here, if you have anything you would like to add or change, let me know
- #92 

@cshadek @NeedleInAJayStack

**Comment by NeedleInAJayStack** [comment]
Thank you for the great contribution @d-exclaimation!
