### ISSUE TITLE
How do you include a ConnectionType in a PartialSchema?

### ISSUE THREAD

**Issue by cshadek** [GraphQLSwift/Graphiti#94]
I was just attempting to try out the new `PartialSchema` feature from @d-exclaimation and noticed that it throws an error if I include a `ConnectionType`.

I also tried `Unions`, `Enums`, `Inputs`, and `Types`, and they all worked!

**Comment by cshadek** [comment]
After looking at it further, I actually think this may be an issue with `SchemaBuilder`, since `PartialSchema` uses `SchemaBuilder` under the hood.

@NeedleInAJayStack, is this the case?

**Comment by NeedleInAJayStack** [comment]
Whoops, sorry about that! I always forget about connections since they aren't part of the base GraphQL spec!

I have a fix for this here: https://github.com/GraphQLSwift/Graphiti/pull/95
