### ISSUE TITLE
The order of PartialSchemas matters for Interfaces, Unions, and ConnectionTypes - is this intentional?

### ISSUE THREAD

**Issue by cshadek** [GraphQLSwift/Graphiti#96]
I noticed that when partial schemas are used to build a new schema, that the order of them matters.  This creates a number of issues, including the potential for a circular reference issue that used to happen and was fixed in #84.  I think it would be better if the schemas were all evaluated together at the same time.  

For example, right now if `SchemaB` depends on an Interface in `SchemaA`, then `SchemaA` has to be listed first in the builder array.  From my understanding, the current implementation makes it impossible to have two schemas that each depend on a field from the other.

@d-exclaimation @NeedleInAJayStack I'm not sure if this an issue with `SchemaBuilder` or `PartialSchema`

**Comment by cshadek** [comment]
As a side note, I'm really excited to refactor my existing 1500+ line schema and start using PartialSchemas!  I've already noticed a lot of improvement with the code completion in the smaller schemas while trying them out.

**Comment by d-exclaimation** [comment]
I'll take a look at this. I am assuming the problem is about using those types in a query, mutation, or subscription field(s) require them to be in the correct order.

**Comment by cshadek** [comment]
@d-exclaimation Interesting.  It also is an issue if an interface is after a type that implements it.

**Comment by d-exclaimation** [comment]
> @d-exclaimation Interesting. It also is an issue if an interface is after a type that implements it.
Got it. I was able to reproduce the issue. I noticed this is also might be a problem with just regular Schema, where intefaces need be declared before any types that uses it

**Comment by NeedleInAJayStack** [comment]
Yeah, I am able to recreate too. Ideally no ordering should be required - I'll look at fixing this tonight. Thanks for reporting @cshadek

**Comment by d-exclaimation** [comment]
> Yeah, I am able to recreate too. Ideally no ordering should be required - I'll look at fixing this tonight. Thanks for reporting @cshadek

Not sure exactly how to properly fix this, but one idea I had is to sort the component declared by like a priority, for example:

Scalars > Enums > Inputs > Interface > Type (Object) > Union > Query > Mutation > Subscription 

I guess this would have solve the case where something like a Union is referenced by a Type (Object), Interfaces, or other Unions. However, so far this method seems to work

**Comment by NeedleInAJayStack** [comment]
@d-exclaimation lol, that's exactly what I did! Great minds think alike!

@cshadek could you try this https://github.com/GraphQLSwift/Graphiti/pull/97 and validate that it fixes your `Connection` issue as well?

**Comment by cshadek** [comment]
@NeedleInAJayStack I just tried a bunch of orders for Connections, Unions, Types, and Interfaces and they all worked.  Nice work!
